# Generated by Django 5.1.2 on 2024-10-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aboutus_miniblocks_miniblocksmain_ourstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns.image.url')),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Campaigns blocks',
                'verbose_name_plural': 'Campaigns blocks',
            },
        ),
        migrations.CreateModel(
            name='GraphicDesignBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='graphic_design.image.url')),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graphic Design blocks',
                'verbose_name_plural': 'Graphic Design blocks',
            },
        ),
        migrations.CreateModel(
            name='WebDisineBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='web_desine.image.url')),
                ('link_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Web Disine blocks',
                'verbose_name_plural': 'Web Disine blocks',
            },
        ),
        migrations.RenameModel(
            old_name='WorkNameMain',
            new_name='WorkseMain',
        ),
        migrations.DeleteModel(
            name='WorkBlocks',
        ),
        migrations.AlterModelOptions(
            name='worksemain',
            options={'verbose_name': 'Works Main', 'verbose_name_plural': 'Works Main'},
        ),
    ]
