# Generated by Django 5.1.2 on 2024-10-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_campaignsblocks_graphicdesignblocks_webdisineblocks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebDisineBlocks',
            new_name='WebDesineBlocks',
        ),
        migrations.RenameModel(
            old_name='WorkseMain',
            new_name='WorksMain',
        ),
        migrations.AlterModelOptions(
            name='webdesineblocks',
            options={'verbose_name': 'Web Desine blocks', 'verbose_name_plural': 'Web Desine blocks'},
        ),
    ]
