# Generated by Django 5.1.2 on 2024-10-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_webdisineblocks_webdesineblocks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignsblocks',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='graphicdesignblocks',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='webdesineblocks',
            name='link_url',
        ),
        migrations.AddField(
            model_name='campaignsblocks',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to='wcampaigns.image.url'),
        ),
        migrations.AddField(
            model_name='graphicdesignblocks',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to='graphic_design.image.url'),
        ),
        migrations.AddField(
            model_name='webdesineblocks',
            name='link_image',
            field=models.ImageField(blank=True, null=True, upload_to='web_desine.image.url'),
        ),
    ]
