# Generated by Django 5.1.2 on 2024-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_campaignsblocks_link_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDesignBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='web_desine.image.url')),
                ('link_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Web Desine blocks',
                'verbose_name_plural': 'Web Desine blocks',
            },
        ),
        migrations.DeleteModel(
            name='WebDesineBlocks',
        ),
        migrations.AlterField(
            model_name='campaignsblocks',
            name='link_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='graphicdesignblocks',
            name='link_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
