# Generated by Django 5.1.2 on 2024-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_campaignsblock1_campaignsblock2_graphicdesignblock1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignsblock2',
            old_name='video',
            new_name='url_video',
        ),
        migrations.RenameField(
            model_name='graphicdesignblock2',
            old_name='video',
            new_name='url_video',
        ),
        migrations.RenameField(
            model_name='webdesignblock2',
            old_name='video',
            new_name='url_video',
        ),
        migrations.AddField(
            model_name='campaignsblock1',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns1.image.url'),
        ),
        migrations.AddField(
            model_name='campaignsblock2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns2.image.url'),
        ),
        migrations.AddField(
            model_name='graphicdesignblock1',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='graphic_design1.image.url'),
        ),
        migrations.AddField(
            model_name='graphicdesignblock2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='graphic_design2.image.url'),
        ),
        migrations.AddField(
            model_name='webdesignblock1',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='web_design1.image.url'),
        ),
        migrations.AddField(
            model_name='webdesignblock2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web_design2.image.url'),
        ),
        migrations.AlterField(
            model_name='campaignsblock1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns1.image.url'),
        ),
        migrations.AlterField(
            model_name='graphicdesignblock1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='graphic_design1.image.url'),
        ),
        migrations.AlterField(
            model_name='webdesignblock1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='web_design1.image.url'),
        ),
    ]
