# Generated by Django 5.1.2 on 2024-10-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_video_campaignsblock2_url_video_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignsblock1',
            options={'verbose_name': 'Campaigns block1', 'verbose_name_plural': 'Campaigns block1'},
        ),
    ]
