# Generated by Django 5.1.2 on 2024-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_about_description1_alter_about_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description4',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
