# Generated by Django 5.1.2 on 2024-10-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_about_description1_alter_about_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactphone',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactphone',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
