# Generated by Django 5.1.2 on 2024-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_openinghours_alter_galleryblocks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('description1', models.CharField(blank=True, max_length=2000, null=True)),
                ('description2', models.CharField(blank=True, max_length=2000, null=True)),
                ('title2', models.CharField(max_length=200)),
                ('description3', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Products Blocks',
                'verbose_name_plural': 'Products Blocks',
            },
        ),
    ]
